version: '3.9'

networks:
  web_network:
    name: network
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: php:8
    container_name: php
    restart: always
    volumes:
      - ./www:/var/www
    networks:
      - web_network
  
  db:
    image: mariadb:10.3.34
    container_name: mariadb
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=comgig
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=1234
    ports:
      - "3308:3306"
    restart: always
    networks:
      - web_network
  
  nginx:
    image: nginx:1.20.2
    container_name: nginx
    volumes:
      - ./www:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "88:80"
    restart: always
    networks:
      - web_network
  
  phpmyadmin:
    image: phpmyadmin:5.1.3
    depends_on:
      - db
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_USER: admin
      # PMA_PASSWORD: 3489
      PWA_ARBITRARY: 1
    ports:
      - 89:80
    restart: always
    tty: true
    networks:
      - web_network


